### ISSUE TITLE
Rendering of sub-pane for an individual contact is broken

### ISSUE THREAD

**Issue by timbl** [solid/contacts-pane#9]
Uncaught (in promise) TypeError: Cannot read property 'render' of null
    at cardPane (mashlib.js:formatted:67791)
    at mashlib.js:formatted:67779
    at mashlib.js:formatted:1610

**Comment by kevin-howard-jd** [comment]
@timbl What were you trying to do when you got the error? Tried to replicate on dev.inrupt.net and and contact pane renders correctly without error. Was there something different about the contact?

**Comment by megoth** [comment]
@timbl Could you verify that this is still the case on dev.inrupt.net?

**Comment by bourgeoa** [comment]
Can be closed. It is working correctly. Code has been largely rewritten.
